import { CATEGORY_COLORS } from "../constants";

export const styles = {
  app: {
    minHeight: "100vh",
    background: "#0f0f14",
    color: "#e8e6f0",
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    background: "rgba(255,255,255,0.03)",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    padding: "0 2rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "60px",
    position: "sticky",
    top: 0,
    zIndex: 100,
    backdropFilter: "blur(10px)",
  },
  logo: {
    fontSize: "18px",
    fontWeight: "700",
    letterSpacing: "-0.5px",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  logoAccent: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    background: "#7c6ded",
    display: "inline-block",
  },
  nav: {
    display: "flex",
    gap: "4px",
  },
  navBtn: (active) => ({
    background: active ? "rgba(124,109,237,0.15)" : "transparent",
    border: active ? "1px solid rgba(124,109,237,0.4)" : "1px solid transparent",
    color: active ? "#a89ff0" : "#8a9bb0",
    padding: "6px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
    transition: "all 0.15s",
  }),
  main: {
    flex: 1,
    padding: "2rem",
    maxWidth: "960px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
  },
  pageTitle: {
    fontSize: "26px",
    fontWeight: "700",
    marginBottom: "1.5rem",
    letterSpacing: "-0.5px",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1rem",
    marginBottom: "1.5rem",
  },
  grid4: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "1rem",
    marginBottom: "1.5rem",
  },
  card: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.07)",
    borderRadius: "14px",
    padding: "1.25rem",
  },
  statCard: (color) => ({
    background: "rgba(255,255,255,0.04)",
    border: `1px solid ${color}30`,
    borderRadius: "14px",
    padding: "1.25rem",
    borderLeft: `3px solid ${color}`,
  }),
  statLabel: {
    fontSize: "12px",
    color: "#8a9bb0",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "6px",
  },
  statValue: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#fff",
  },
  statSub: {
    fontSize: "12px",
    color: "#8a9bb0",
    marginTop: "4px",
  },
  sectionTitle: {
    fontSize: "15px",
    fontWeight: "600",
    marginBottom: "1rem",
    color: "#c0b8e0",
  },
  expenseItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 0",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  expenseLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  categoryDot: (cat) => ({
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    background: `${CATEGORY_COLORS[cat] || "#8a9bb0"}20`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    color: CATEGORY_COLORS[cat] || "#8a9bb0",
    fontWeight: "700",
    flexShrink: 0,
  }),
  expenseTitle: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#e0dff0",
    marginBottom: "2px",
  },
  expenseMeta: {
    fontSize: "12px",
    color: "#6a7b8e",
  },
  expenseAmount: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#fff",
  },
  deleteBtn: {
    background: "transparent",
    border: "none",
    color: "#6a7b8e",
    cursor: "pointer",
    fontSize: "16px",
    padding: "4px 8px",
    borderRadius: "6px",
    marginLeft: "12px",
    transition: "all 0.15s",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontSize: "13px",
    color: "#8a9bb0",
    fontWeight: "500",
  },
  input: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "10px",
    padding: "10px 14px",
    color: "#e8e6f0",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "inherit",
    transition: "border 0.15s",
  },
  select: {
    background: "#1a1a24",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "10px",
    padding: "10px 14px",
    color: "#e8e6f0",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "inherit",
    cursor: "pointer",
  },
  submitBtn: {
    background: "linear-gradient(135deg, #7c6ded, #9d6ded)",
    border: "none",
    borderRadius: "10px",
    padding: "12px",
    color: "#fff",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "opacity 0.15s",
    marginTop: "4px",
  },
  badge: (cat) => ({
    background: `${CATEGORY_COLORS[cat] || "#8a9bb0"}20`,
    color: CATEGORY_COLORS[cat] || "#8a9bb0",
    padding: "2px 8px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "600",
  }),
  filterBar: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap",
    marginBottom: "1.25rem",
  },
  filterChip: (active) => ({
    background: active ? "rgba(124,109,237,0.2)" : "rgba(255,255,255,0.04)",
    border: active ? "1px solid rgba(124,109,237,0.5)" : "1px solid rgba(255,255,255,0.08)",
    color: active ? "#a89ff0" : "#8a9bb0",
    padding: "5px 14px",
    borderRadius: "20px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "500",
    transition: "all 0.15s",
  }),
  progressBar: (pct, color) => ({
    height: "6px",
    borderRadius: "4px",
    background: `${color}30`,
    position: "relative",
    overflow: "hidden",
    marginTop: "8px",
  }),
  progressFill: (pct, color) => ({
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    width: `${Math.min(pct, 100)}%`,
    background: color,
    borderRadius: "4px",
    transition: "width 0.6s ease",
  }),
  budgetRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "6px",
  },
  emptyState: {
    textAlign: "center",
    padding: "3rem",
    color: "#6a7b8e",
    fontSize: "14px",
  },
  successToast: {
    position: "fixed",
    bottom: "2rem",
    right: "2rem",
    background: "#1e2a1e",
    border: "1px solid #3dbf7e40",
    color: "#3dbf7e",
    padding: "12px 20px",
    borderRadius: "10px",
    fontSize: "13px",
    fontWeight: "500",
    zIndex: 999,
    animation: "slideIn 0.3s ease",
  },
  row2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "1rem",
  },
  textarea: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "10px",
    padding: "10px 14px",
    color: "#e8e6f0",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    fontFamily: "inherit",
    resize: "vertical",
    minHeight: "70px",
  },
};
